lang: en
retain_result: null
# retain_result: ${hydra:runtime.cwd}/outputs/tofu_finetuned_5epoch_aya_retain_10_lang_2e5_full/eval_results/ds_sizeNone_${lang}/eval_log_aggregated.json
# ckpt_result: ${hydra:runtime.cwd}/outputs/tofu_finetuned_5epoch_llama/eval_results/ds_sizeNone_${lang}/eval_log_aggregated.json
ckpt_result: ${hydra:runtime.cwd}/outputs/tofu_finetuned_5epoch_aya_10_lang_2e5/grad_diff_2e-05_forget01_5_en/eval_results/ds_sizeNone_${lang}/eval_log_aggregated.json
method_name: grad_diff
submitted_by: RCG
save_file: ${hydra:runtime.cwd}/results/aya_graddiff_10lang/finetune_result01_unlearn_grad_diff_2e-05_${lang}.csv
